name: Python CI (testing)

on: [push, pull_request]

jobs:

  build:
    name: Build package
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python3 -m pip install -e .
          python3 -m pip install black flake8 pytype isort
    
      - name: Type check
        run: |
          pytype -j auto ./

      - name: Check codestyle
        run: |
          isort --check ./
          black --check ./
    
      - name: Lint with flake8
        run: |
          flake8 ./ --count --show-source --statistics
  test:
    name: Test package
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          sudo apt-get install graphviz
          python3 -m pip install -e .

      - name: Run Learner
        run: |
          python3 -m rl_toolkit --mode learner -e AntBulletEnv-v0 -t 1
    
      - name: Run Tester
        run: |
          python3 -m rl_toolkit --mode tester -e AntBulletEnv-v0 -t 1
